# Generated by Django 5.2.17 on 2026-08-08 19:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=10)),
                ('insurance_law', models.CharField(choices=[('RET', 'معاش ق79'), ('STD', 'طلبة'), ('CID', 'مواليد ق99'), ('EMP', 'موظف ق79')], max_length=10)),
                ('insurance_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('affiliated_branch', models.CharField(choices=[('AST', 'فرع اسيوط'), ('BHR', 'فرع البحيرة'), ('GIZ', 'فرع الجيزة'), ('DKH', 'فرع الدقهلية'), ('SHR', 'فرع الشرقية'), ('GHB', 'فرع الغربية'), ('FYM', 'فرع الفيوم'), ('CAI', 'فرع القاهرة'), ('QLY', 'فرع القليوبية'), ('MNF', 'فرع المنوفية'), ('MNY', 'فرع المنيا'), ('BNS', 'فرع بنى سويف'), ('DMT', 'فرع دمياط'), ('SHG', 'فرع سوهاج'), ('NSN', 'فرع شمال سيناء'), ('NWD', 'فرع شمال غرب الدلتا'), ('QNA', 'فرع قنا'), ('KSH', 'فرع كفر الشيخ'), ('RDS', 'منطقة البحر الاحمر'), ('NWV', 'منطقة الوادى الجديد'), ('MTR', 'منطقة مطروح')], max_length=100)),
                ('diagnosis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('requires_referral', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('PREPARING', 'قيد التجهيز'), ('COMPLETED', 'مكتملة')], default='PREPARING', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='committee.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'معتمد')], default='PENDING', max_length=20)),
                ('committee_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='committee.committeesession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee_cases', to='committee.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_sessions', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('recommendation_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='committee.committeecase')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='committee.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ISSUED', 'صادر'), ('CANCELLED', 'ملغي')], default='ISSUED', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('committee_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='committee.committeecase')),
                ('referral_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='committee.referralcenter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='committeesession',
            constraint=models.UniqueConstraint(fields=('session_date',), name='unique_session_per_day'),
        ),
        migrations.AddConstraint(
            model_name='committeecase',
            constraint=models.UniqueConstraint(fields=('committee_session', 'patient'), name='unique_patient_per_session'),
        ),
    ]
