# Generated by Django 5.2.17 on 2026-08-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='price_in_words',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
