# Generated by Django 5.2.17 on 2026-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_procedure_price_in_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
