# Generated by Django 5.2.17 on 2026-09-16 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnosis_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='committee.diagnosis'),
        ),
    ]
