# Generated by Django 5.2.17 on 2026-09-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_patient_diagnosis_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis_temp',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
